version: "3.8"

services:
  web:
    image: gtd-xxvi/website
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    ports:
      - 3000:3000

  proxy:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - web
