name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
  STRIPE_SECRET_KEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.DEV_STRIPE_WEBHOOK_SECRET }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.DEV_STRIPE_PUBLISHABLE_KEY }}
  AUTH_SECRET: ${{ secrets.DEV_AUTH_SECRET }}
  BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}

jobs:
  build:
    name: Development build
    uses: ./.github/workflows/development-build.yaml
    secrets: inherit
  test:
    name: Run tests
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  deploy:
    needs: [build, test]
    if: always()
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
          envkey_STRIPE_SECRET_KEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
          envkey_STRIPE_WEBHOOK_SECRET: ${{ secrets.DEV_STRIPE_WEBHOOK_SECRET }}
          envkey_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.DEV_STRIPE_PUBLISHABLE_KEY }}
          envkey_AUTH_SECRET: ${{ secrets.DEV_AUTH_SECRET }}
          envkey_BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          fail_on_empty: true
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
